backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Descrizione", name: "description", widget: "text" }
